// Package registry owns everything mon-server knows about its mon-clients:
// the registration requests boxes file, the client tokens approval issues,
// the registry rows the admin UI manages and the authentication of every
// authenticated /v1 call (spec mon-server.md §6, mon-protocol.md §2–3).
//
// It is the only package that mints or verifies a client token. The plaintext
// exists twice and briefly: once in the answer to the mon-client's first poll,
// and once in registration_requests.approved_token until that poll collects
// it. Everywhere else a token is the hex SHA-256 of store.HashToken.
//
// The service takes its time from the store's clock.Clock, so registration
// TTLs and rate limits are driven by clock.Fake in tests, and it files every
// event through internal/events rather than writing events_outbox itself.
package registry

import (
	"errors"
	"fmt"
	"log/slog"
	"regexp"
	"sync"
	"time"

	"github.com/SBKubric/3ax-ui-monitoring/internal/api"
	"github.com/SBKubric/3ax-ui-monitoring/internal/clock"
	"github.com/SBKubric/3ax-ui-monitoring/internal/events"
	"github.com/SBKubric/3ax-ui-monitoring/internal/store"
)

// Registration limits and shapes of spec §6 and mon-protocol.md §2.1.
const (
	// RequestTTL is how long a registration request stays pending.
	RequestTTL = 5 * time.Minute
	// PollAfterMS is the poll interval mon-server asks the mon-client for.
	PollAfterMS int64 = 10_000
	// MinSubmitInterval is the per-IP request rate: one a minute.
	MinSubmitInterval = time.Minute
	// MaxPendingPerIP is how many requests one IP may have waiting.
	MaxPendingPerIP = 3
	// MaxPendingTotal is how many requests may be waiting altogether.
	MaxPendingTotal = 20
	// MaxRetryAfter caps the Retry-After hint of a refused request, so a
	// mon-client is never told to wait longer than a request can live.
	MaxRetryAfter = RequestTTL

	// requestIDBytes is the size of the polling secret: 128 bits.
	requestIDBytes = 16
	// tokenBytes is the size of a client token (mon-protocol.md §3).
	tokenBytes = 32
	// maxMonClientIDLen mirrors the id column (spec §3).
	maxMonClientIDLen = 64

	maxHostnameLen = 255
	maxVersionLen  = 64
	maxIPLen       = 64
)

// pairingCodePattern is the shape of a pairing code. The code is generated by
// the mon-client and read out by the administrator; mon-server only checks
// that it looks like one (spec §6).
var pairingCodePattern = regexp.MustCompile(`^[A-Z2-9]{6}$`)

// The registration types cross into internal/api, which declares the port the
// two /v1/register handlers are written against. They are aliases, not copies,
// so that *Registry satisfies api.RegistrationService directly.
type (
	// SubmitRequest is one POST /v1/register.
	SubmitRequest = api.RegistrationSubmit
	// SubmitResult is what the mon-client is told to poll with.
	SubmitResult = api.RegistrationSubmitted
	// PollResult is the answer to one GET /v1/register/{requestId}.
	PollResult = api.RegistrationStatus
)

// Sentinel errors. The four that the /v1 handlers branch on are declared in
// internal/api, the port they belong to, and named here for callers of this
// package; the rest are the admin UI's.
var (
	// ErrInvalidRequest is a registration request that cannot be accepted as
	// written. Every validation failure below wraps it.
	ErrInvalidRequest = api.ErrRegistrationInvalid
	// ErrRateLimited is any of the three limits of spec §6 refusing a
	// request. Every RateLimitError wraps it.
	ErrRateLimited = api.ErrRegistrationRateLimited
	// ErrRequestNotFound is an unknown requestId.
	ErrRequestNotFound = api.ErrRegistrationNotFound
	// ErrRequestExpired is a request past RequestTTL.
	ErrRequestExpired = api.ErrRegistrationExpired

	// ErrInvalidPairingCode reports a pairing code that is not [A-Z2-9]{6}.
	ErrInvalidPairingCode = fmt.Errorf("%w: pairing code must be six characters of [A-Z2-9]", ErrInvalidRequest)
	// ErrHostnameTooLong, ErrVersionTooLong and ErrPublicIPTooLong report a
	// field longer than its column.
	ErrHostnameTooLong = fmt.Errorf("%w: hostname is too long", ErrInvalidRequest)
	ErrVersionTooLong  = fmt.Errorf("%w: version is too long", ErrInvalidRequest)
	ErrPublicIPTooLong = fmt.Errorf("%w: public ip is too long", ErrInvalidRequest)

	// ErrIPRateLimited reports the one-request-per-minute-per-IP limit.
	ErrIPRateLimited = errors.New("registry: one registration request per minute and IP")
	// ErrTooManyPendingForIP reports the three-pending-per-IP limit.
	ErrTooManyPendingForIP = errors.New("registry: too many pending registration requests from this IP")
	// ErrTooManyPendingGlobal reports the twenty-pending-overall limit.
	ErrTooManyPendingGlobal = errors.New("registry: too many pending registration requests")

	// ErrRequestNotPending reports an approval or rejection of a request that
	// has already been decided.
	ErrRequestNotPending = errors.New("registry: registration request is not pending")
	// ErrEmptyName reports a name whose slug is empty, so no id can be made
	// of it.
	ErrEmptyName = errors.New("registry: name has no slug")
	// ErrInvalidPaths reports an empty path set or a path that is neither
	// proxy nor direct.
	ErrInvalidPaths = errors.New("registry: paths must be a non-empty subset of proxy and direct")
	// ErrMonClientNotFound reports an unknown mon-client id.
	ErrMonClientNotFound = errors.New("registry: mon-client not found")
	// ErrNoFreeID reports that no unique id could be derived from a name,
	// which takes a thousand mon-clients of the same name.
	ErrNoFreeID = errors.New("registry: no free mon-client id for this name")
)

// RateLimitError is a registration request refused by one of the limits of
// spec §6. It names the limit and how long the mon-client should wait, which
// the handler turns into the Retry-After header of its 429.
type RateLimitError struct {
	// Limit is ErrIPRateLimited, ErrTooManyPendingForIP or
	// ErrTooManyPendingGlobal.
	Limit error
	// Wait is the Retry-After hint.
	Wait time.Duration
}

// Error implements error.
func (e *RateLimitError) Error() string {
	return fmt.Sprintf("%s: retry after %s", e.Limit, e.Wait.Round(time.Second))
}

// Unwrap makes both errors.Is(err, ErrRateLimited) and errors.Is(err, <the
// specific limit>) true.
func (e *RateLimitError) Unwrap() []error { return []error{e.Limit, ErrRateLimited} }

// RetryAfter is the hint the /v1 handler reads structurally.
func (e *RateLimitError) RetryAfter() time.Duration { return e.Wait }

// Registry is the registration and registry service. It is safe for
// concurrent use: the read-modify-write sequences — checking a rate limit,
// deriving a unique id, handing out a one-shot token — are serialised, and
// everything else is a single statement.
type Registry struct {
	st  *store.Store
	ob  *events.Outbox
	log *slog.Logger
	clk clock.Clock

	// mu guards the decisions that read the database and then write it.
	mu sync.Mutex
}

// New returns a Registry over st. ob may be nil, meaning events are filed with
// no Telegram fallback; log may be nil, meaning the service is silent.
func New(st *store.Store, ob *events.Outbox, log *slog.Logger) *Registry {
	if ob == nil {
		ob = events.New(st, nil)
	}
	if log == nil {
		log = slog.New(slog.DiscardHandler)
	}
	return &Registry{st: st, ob: ob, log: log, clk: st.Clock()}
}

// The two ports this service fills: the registration endpoints of
// mon-protocol.md §2 and the client-token check of §3.
var (
	_ api.RegistrationService = (*Registry)(nil)
	_ api.Authenticator       = (*Registry)(nil)
)

// nowMS is the current time in the storage form, from the injected clock.
func (r *Registry) nowMS() int64 { return clock.MS(r.clk.Now()) }

// capWait keeps a Retry-After hint inside [1s, MaxRetryAfter].
func capWait(d time.Duration) time.Duration {
	if d < time.Second {
		return time.Second
	}
	if d > MaxRetryAfter {
		return MaxRetryAfter
	}
	return d
}
