// Package xraytest builds the fake xray binary (internal/client/xray's
// testdata/fakexray) for tests that live outside internal/client/xray.
//
// It exists because applying a config revision (spec §4 step 3) is the one
// thing that cannot be tested without a child process to run `-test` and
// restart: internal/client/app has to drive a real *xray.Process, and
// docs/agents/testing.md rules out the real xray binary in unit tests. The
// xray package's own TestMain builds the same program; this package is that
// build, exported, so there is exactly one fake xray in the repository.
package xraytest

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sync"
	"testing"
)

// Script is the "fake" section of a fakexray config, handed to the binary
// out of band through the FAKEXRAY_SCRIPT environment variable.
//
// Out of band because the config mon-client feeds the child is generated by
// config.BuildXray and has no room for test knobs in it: the apply path must
// write exactly the bytes production writes, or the test stops testing the
// apply path.
type Script struct {
	// TestFail makes `-test` print this line and exit non-zero — a config
	// xray rejects (spec §4 step 3's "-test упал").
	TestFail string `json:"testFail,omitempty"`
	// ExitNow makes `run` print ExitMsg and exit before it listens.
	ExitNow bool   `json:"exitNow,omitempty"`
	ExitMsg string `json:"exitMsg,omitempty"`
	// DelayMs delays binding the socks ports.
	DelayMs int `json:"delayMs,omitempty"`
	// Stderr lines are printed before the ports come up, Stderr2 after.
	Stderr  []string `json:"stderr,omitempty"`
	Stderr2 []string `json:"stderr2,omitempty"`
	// IgnoreSIGTERM makes `run` ignore SIGTERM.
	IgnoreSIGTERM bool `json:"ignoreSigterm,omitempty"`
}

// ScriptEnv is the environment variable fakexray reads a Script from.
const ScriptEnv = "FAKEXRAY_SCRIPT"

var (
	buildMu   sync.Mutex
	buildOnce sync.Once
	buildBin  string
	buildErr  error
)

// Build compiles testdata/fakexray once per test binary and returns the path
// to it, skipping the test when there is no Go toolchain to build it with
// (the same condition internal/client/xray's own TestMain skips on).
//
// The binary is left in a temporary directory for the lifetime of the test
// process: every test in the package shares one build, and removing it after
// the first caller's t finished would break the rest.
func Build(t *testing.T) string {
	t.Helper()
	buildMu.Lock()
	defer buildMu.Unlock()
	buildOnce.Do(func() { buildBin, buildErr = build() })
	if buildErr != nil {
		t.Skipf("fakexray unavailable: %v", buildErr)
	}
	return buildBin
}

// Cleanup removes the directory Build compiled into, if it compiled one.
// It belongs in the TestMain of every package that calls Build: the binary
// has to outlive each individual test (they share one build), so the only
// place left to remove it is after the whole test binary is done — and
// os.Exit, which TestMain ends with, runs no deferred function.
func Cleanup() {
	buildMu.Lock()
	defer buildMu.Unlock()
	if buildBin != "" {
		_ = os.RemoveAll(filepath.Dir(buildBin))
		buildBin = ""
	}
}

// Scripted points fakexray at s for the duration of the test. It uses
// t.Setenv, so a test that calls it cannot be parallel — which is the right
// constraint anyway: it is scripting a process the whole test drives.
func Scripted(t *testing.T, s Script) {
	t.Helper()
	raw, err := json.Marshal(s)
	if err != nil {
		t.Fatalf("marshal fakexray script: %v", err)
	}
	path := filepath.Join(t.TempDir(), "fakexray-script.json")
	if err := os.WriteFile(path, raw, 0o600); err != nil {
		t.Fatalf("write fakexray script: %v", err)
	}
	t.Setenv(ScriptEnv, path)
}

// build compiles the fake from this package's sibling testdata directory,
// found through runtime.Caller so it does not depend on the working
// directory of whichever package's test is running.
func build() (string, error) {
	if _, err := exec.LookPath("go"); err != nil {
		return "", err
	}
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("cannot locate the xraytest source directory")
	}
	src := filepath.Join(filepath.Dir(filepath.Dir(file)), "testdata", "fakexray")

	dir, err := os.MkdirTemp("", "fakexray")
	if err != nil {
		return "", err
	}
	bin := filepath.Join(dir, "fakexray")
	out, err := exec.Command("go", "build", "-o", bin, src).CombinedOutput()
	if err != nil {
		_ = os.RemoveAll(dir)
		return "", fmt.Errorf("go build: %v: %s", err, out)
	}
	return bin, nil
}
